name: Deploy Web App

on:
  push:
#    branches:
#      - main  # Adjust if needed
  workflow_dispatch: # Allows manual triggering of the workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # Ensure SERVER_HOST is defined in repository secrets
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export HOME=/home/jon
            export NVM_DIR="$HOME/.nvm"
            echo "Load nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            echo "Starting deployment process.  Home: $HOME  " > /home/jon/deployment.log
            tmux kill-session -t notes || true
            cd ~/projects/NoteShare
            git stash -m "Deployment stash"
            echo "Pulling latest changes from main branch"
            git pull origin main
            echo "Applying stashed changes"
            git stash apply            
            echo "Installing dependencies"
            /home/jon/.nvm/versions/node/v20.11.0/bin/npm install
            echo "Building the application"
            /home/jon/.nvm/versions/node/v20.11.0/bin/npm run build
            echo "Starting the application in a new tmux session"
            tmux new-session -d -s notes '/home/jon/.nvm/versions/node/v20.11.0/bin/node server.js'
