name: Deploy Web App

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # Ensure SERVER_HOST is defined in repository secrets
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            tmux kill-session -t notes || true
            cd ~/projects/NoteShare
            git stash -m "Deployment stash"
            git pull origin main
            git stash apply
            npm run build
            tmux new-session -d -s notes 'node server.js'
